openapi: 3.1.0
info:
  version: 1.0.0
  title: MindFlow Backend API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: A RESTful backend service for a contact management web application. It provides secure user authentication (registration, login, token-based access) and full CRUD functionality for managing personal contact data. Built with scalability and security in mind, the API ensures that each user's data is isolated and protected.
tags:
  - name: Index
    description: Check server.
servers:
  - url: http://localhost:3000
  - url: https://mindflow-backend-iwk7.onrender.com
paths:
  /:
    get:
      $ref: ../swagger/paths/index/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
